
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456781303
      POSTGRES_DB: navaapidb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
