services:
  spring-nava-api:
    build: .
    container_name: spring-nava-api-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/navaapidb?useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456781303
      SPRING_ELASTICSEARCH_URIS: elasticsearch:9200
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME: docker-cluster
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/src/spring-nava-api/
    stdin_open: true
    tty: true